apiVersion: apps/v1
kind: Deployment
metadata:
  name: finalorder
  labels:
    app: finalorder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finalorder
  template:
    metadata:
      labels:
        app: finalorder
    spec:
      containers:
        - name: finalorder
          image: jinunkim/finalorder:0407
          ports:
            - containerPort: 8080
          resources:
              limits:
                cpu: 500m
              requests:
                cpu: 200m